### ISSUE TITLE
deploy_path wildcard support

### ISSUE THREAD

**Issue by cnadeau** [bitrise-steplib/steps-deploy-to-bitrise-io#110]
HI, we're building different projects using the same bitrise.yml and I would like a generic way to upload the ipa as an artifact

Using
```
deploy_path: /Users/vagrant/git/*.ipa
```

actually finds the ipa, but the uploader fails to upload 

```
Deploying files
Uploading ipa file: /Users/vagrant/git/*.ipa
analyzing ipa
  ipa infos: map[app_title:Sandbox build_number:28 bundle_id:sandox device_family_list:[2] min_OS_version:12.0 version:1.0]
deploy failed, error: failed to get ipa size, error: file not exist
```

Any idea if this can be done?

Cheers!

**Comment by bitce** [comment]
Hi @cnadeau!

Can you please include a relevant build's URL? What is the solution you're looking for exactly, IPAs are uploaded as artifacts by default behaviour, so it's not completely clear to me
