### ISSUE TITLE
How to utilize when running locally?

### ISSUE THREAD

**Issue by kceb** [bitrise-steplib/steps-deploy-to-bitrise-io#117]
I'd like to be able to utilize the deploy to bitrise io step when running locally with bitrise CLI. This gives me the ability to install the iOS app on mobile devices because of the extra "Check if this app is compatible with your phone" step which downloads a configuration profile. I'm not sure how to easily download the app otherwise. If I were to upload the .ipa to S3, there wouldn't be an option to download and install the configuration profile.

Is there a way to do this? It seems like the deploy to bitrise step is coupled to a bitrise build, not a local build.

**Comment by non-binary** [comment]
Hi @kceb,

Are you looking for assistance with this still?

If so, please let us know and I'll look into it for you. If not, please share your answer and close ticket.

Thanks,
Luna

**Comment by kceb** [comment]
I have opted for using diawi to host my ipa/apk files.
