### ISSUE TITLE
Show SHA256 of debug.keystore for configuring Google login

### ISSUE THREAD

**Issue by paramaggarwal** [bitrise-steplib/steps-deploy-to-bitrise-io#119]
Our app uses Google login, which is configured via Firebase, which verified app source using the `SHA256` signature of the signing keystore.

We are creating a temporary keystore and we need to mention the SHA256 signature in the README otherwise suddenly login stops working.

https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/blob/b74fb07f34f8a76469896e2116b1f8932826a254/aabutil.go#L38-L51

**Comment by Roland-Bak** [comment]
Hi there @paramaggarwal!

If you need to mention the SHA256 signature in your readme file, you can append it to the end of your file via a script step: 

`sha256sum /path/to/debug.keystore >> README.md`

(In case you are running on mac you would need to run `brew install coreutils` to get sha256sum beforehand)

Hope this helps :)

**Comment by paramaggarwal** [comment]
Thanks 👍
