### ISSUE TITLE
[Feature Request] Option to use custom keystore when generating Universal APK from AAB

### ISSUE THREAD

**Issue by paramaggarwal** [bitrise-steplib/steps-deploy-to-bitrise-io#121]
## Problem
The APK is signed using a temporary debug key - this causes problems like the one mentioned in https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/119. Kindly give an option to use a custom keystore instead.

## Suggestion
It can pick up the credentials from the code signing variables that configured already in the workflow as standard. Please use these when available, otherwise fall back to what is mentioned above:

- `$BITRISEIO_ANDROID_KEYSTORE_URL`
- `$BITRISEIO_ANDROID_KEYSTORE_PASSWORD`
- `$BITRISEIO_ANDROID_KEYSTORE_ALIAS`
- `$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD`

## Reference
https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/blob/b74fb07f34f8a76469896e2116b1f8932826a254/aabutil.go#L38-L51

**Comment by bitce** [comment]
Thanks for the report @paramaggarwal! Can you please include a build URL we can take a look at here?

**Comment by paramaggarwal** [comment]
I don't wish to share a build URL - my concern is that I would like to give a custom signing credentials and not use the default ones here:

https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/blob/b74fb07f34f8a76469896e2116b1f8932826a254/aabutil.go#L38-L51

**Comment by bitce** [comment]
Understood completely! It just would have been useful to see logs of the actual behaviour supporting what you describe, but it's your call, of course, thanks for the report 🙂

**Comment by paramaggarwal** [comment]
I can't actually find the logs now because I had used a workaround since that time. I think I have used wrong issue title here... Fixing...

**Comment by paramaggarwal** [comment]
@bitce I am sorry for causing confusion initially. I would like to clarify - this is a feature request and not a bug report. Hence log won't be needed as I can't even find it right now... 

I would like to request a way to give a custom keystore when it generates a universal APK from the AAB. Currently it uses a hardcoded generic keystore which is generated on-the-fly.

I would like to use such env variables to define a custom keystore file that can be used for `bundletool` during this APK signing.

- `$BITRISEIO_ANDROID_KEYSTORE_URL`
- `$BITRISEIO_ANDROID_KEYSTORE_PASSWORD`
- `$BITRISEIO_ANDROID_KEYSTORE_ALIAS`
- `$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD`
