### ISSUE TITLE
Bump to bundletool 0.13.4+

### ISSUE THREAD

**Issue by jamieadkins95** [bitrise-steplib/steps-deploy-to-bitrise-io#123]
Hey guys,

Bundletool 0.13.4 fixes a pretty important issue for us:
https://github.com/google/bundletool/releases/tag/0.13.4

Could you update this step to either use 0.13.4 or 0.14.0?

Thanks!

**Comment by jamieadkins95** [comment]
Fixed in #122 I guess haha

**Comment by androideveloper** [comment]
This can also be closed
