### ISSUE TITLE
Undefined variable "$ANDROID_VERSION_CODE"

### ISSUE THREAD

**Issue by s7aycool** [bitrise-steplib/steps-deploy-to-bitrise-io#125]
Subject

Error on step "deplay to bitrise":
```
deploy to bitriseio@1.10

id: deploytobitriseio
version: 1.10.0
collection : https://github.com/bitriseio/bitrisesteplib.git
toolkit: go
time: 20201014T08:19:46Z

mPublicInstall PageMapFormat template: Public Install PageMap template:1:**undefinedvariable"$ANDROIDVERSIONCODE"**

mdeploytobitriseio@1.10 (exitcode:1) 4.87sec
```

**Comment by bitce** [comment]
Hi there, please include a build URL with your report and enable Support User access in the Settings if possible!

**Comment by s7aycool** [comment]
It's closed project from work. Can I do that?) I don't wanna give you access to our repo.

By the way, I want to mention that I haven't changed any versions of deploy to bitrise, and I my last successful deploy to bitrise was on 15th of september

If you want, I can

**Comment by bitce** [comment]
I see! We won't be able to look into this based on this minor details alone, so please include a build URL either way, that only allows us to check out the build logs, and some metadata about the build, like it's .yml and when it was started, how it was started and such.

Bitrise does not store your source code in any way, Support Access wouldn't give us access to the repository either, but to your complete configuration. We could in theory access your repository in the build machine temporarily by remote accessing into it, but we can't do that without explicit authorization.

**Comment by s7aycool** [comment]
What info from the build you wanna see? Previous steps?

everything is fine.
![image](https://user-images.githubusercontent.com/59872947/96262082-f8168280-0fc9-11eb-9b8f-1fbb06505604.png)

**Comment by s7aycool** [comment]
Have no idea how to include a build url. There are no "share" option for the build =(

**Comment by bitce** [comment]
Please paste here the URL you see in your browsers search bar when you are on a build page. Thanks!

**Comment by s7aycool** [comment]
https://app.bitrise.io/build/bc7a443ca99a7253#?tab=log

**Comment by bitce** [comment]
Thanks! Unfortunately, you won't be able to just paste a variable and have it displayed on your public install page. What is unclear to me, is why would you like to print out #ANDROID_VERSION_CODE there? I'm attaching the default APK public install page, it displays this information by default.

![Screenshot from 2020-10-19 13-22-16](https://user-images.githubusercontent.com/40164469/96444270-461bc800-120e-11eb-97c4-b00d5be175b6.png)

**Comment by s7aycool** [comment]
I have like 200 successful builds with this settings. 

![image](https://user-images.githubusercontent.com/59872947/96847352-bff4c100-145b-11eb-81a3-b5e0702cf299.png)


    - deploy-to-bitrise-io@1.10:
        inputs:
        - notify_user_groups: testers, developers
        - public_install_page_url_map_format: "{{range $index, $element := .}}{{if
            $index}}|{{end}}{{$element.File}}=>{{$element.URL}}-{{$ANDROID_VERSION_CODE}}{{end}}"
        - deploy_path: "$BITRISE_SIGNED_AAB_PATH"

**Comment by bitce** [comment]
Oh I see! Can you send us a successful build like that?

**Comment by s7aycool** [comment]
https://app.bitrise.io/build/8c4c1b3559824a48#?tab=log

**Comment by bitce** [comment]
This build is indeed successful, but has the default `{{range $index, $element := .}}{{if $index}}|{{end}}{{$element.File}}=>{{$element.URL}}{{end}}` for the Public Install page format options. Is there a successful example that contains the variable?

**Comment by s7aycool** [comment]
@bitce I swear I would never add this to my workflow: "-{{$ANDROID_VERSION_CODE}}{{end}}". I don't know where this line came from. And moreover, this line was only in 1 of 3 workflows. Feeling frustrated 

Deploy to bitrise is up now! 

Thanks for the help, and sorry for bothering you +)
