### ISSUE TITLE
Deploy artifacts failing

### ISSUE THREAD

**Issue by pavm035** [bitrise-steplib/steps-deploy-to-bitrise-io#140]
Hi,

After upgrading https://github.com/bitrise-steplib/steps-xcode-archive to 3.2.3 this step is failing, but if i revert back archive tool to 3.1.3 it seems to be fine, based on some investigation got clue that latest `Xcode-Archive` has made changes on extracting .xarchive.zip file, actually we have custom name for artifactory generation like `${scheme}($XPI_BUILD)` i guess due to additional name suffix it might be failing to extract archive file

Error:
deploy failed, error: could not check if given project is macOS or not, error: No file found at path: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__xcarhive__417200365/Release(860003).xcarchive/Info.plist

**Comment by godrei** [comment]
Hi @pavm035 ,
sorry for the inconvenience, you can read more about the issue in the related PR description: https://github.com/bitrise-steplib/steps-xcode-archive/pull/229
The changes released in the new Xcode Archive step version: [3.2.4](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/3.2.4).

I'll close this issue, but if you need more info/help just let us know by opening a new one!
