### ISSUE TITLE
XCode 13 missing "cfBundleVersion"

### ISSUE THREAD

**Issue by spasbilyarski** [bitrise-steplib/steps-deploy-to-bitrise-io#144]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.3.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

The build step doesn't work with the latest XCode stack option. After xcrun upload command the step fails because of missing `cfBundleVersion` in plist (it has CFBundleVersion). 

The issue is reproducible with and without  `set-ios-version`  which I regularly use.

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+

| (8) deploy-to-itunesconnect-application-loader@1                             |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-application-loader                               |
| version: 1.3.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-09-27T07:29:38Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- BitriseConnection: automatic
- AppleID: {REDACTED}
- Password: {REDACTED}
- AppSpecificPassword: 
- APIKeyPath: 
- APIIssuer: 
- IpaPath: /Users/vagrant/deploy/{REDACTED}.ipa
- PkgPath: 
- Platform: auto
- ItunesConnectUser: {REDACTED}
- AdditionalParams: 
- BuildURL: https://app.bitrise.io/build/{REDACTED}
- BuildAPIToken: {REDACTED}
Inputs with Apple ID authentication found.
If 2FA enabled, Application-specific password is required when using Apple ID authentication.
Uploading - {REDACTED}.ipa ...
$ xcrun "altool" "--upload-app" "-f" "/Users/vagrant/deploy/{REDACTED}.ipa" "--type" "ios" "--username" "[REDACTED]" "--password" "[REDACTED]"
*** Error: Exception caught. Exception caught: *** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: cfBundleVersion) (-1010)
Uploading IPA failed: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-application-loader@1 (exit code: 1)   | 10.46 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ib/steps-deploy-to-itunesconnect-application-loader/issues |
| Source: .../bitrise-steplib/steps-deploy-to-itunesconnect-application-loader |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. Use the new "Xcode 13.0.x, on macOS 11.4 (Big Sur)" stack
2. Start a build
3. Look at output

**Comment by lpusok** [comment]
Hello @spasbilyarski, can you please check that you are using the latest Step version? (That is 2.0.0)

**Comment by spasbilyarski** [comment]
Thank you for the reply but I just saw that I posted the issue in the bitrise deploy and not the appstore connect deploy. Sorry for the trouble!
