### ISSUE TITLE
"Enable public page for the App" should default to false

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-deploy-to-bitrise-io#56]
Since this step is auto-added to new projects, I think the public page URL should default to false. I know it generates a random and long URL, but I'd prefer if this was not shared publicly at all. We have been building for a while and didn't realize we'd been exposing our apk on a public install page until now.

**Comment by viktorbenei** [comment]
Thanks for the feature request @tir38 ! :)
