### ISSUE TITLE
Bug on Android build Deploy to Btirise

### ISSUE THREAD

**Issue by panoramix360** [bitrise-steplib/steps-deploy-to-bitrise-io#67]
Hi!

When I changed to the new version of step "Deploy to Bitrise.io" (1.3.14).

My build on Android environment is changing the versionName of the app with a strange string like the following:

Version code: 48
Version Name: 1.1.0' platformBuildVersionName='

![image](https://user-images.githubusercontent.com/2154092/43984840-8793e256-9cd9-11e8-9371-e7b8e7974ffb.png)

I don't know why the string "platformBuildversionName" is being printed with the version name. But when I change to the version 1.3.10 it shows the version normally.

Anyone had this problem too?

Thank you.

**Comment by tamasbazs** [comment]
Hi @panoramix360 ,
Thank you for reporting this issue! Could you send us the URL of the given build?
