### ISSUE TITLE
How iOS build multiple .ipa

### ISSUE THREAD

**Issue by wongkaking** [bitrise-steplib/steps-deploy-to-bitrise-io#80]
Hi, I am Kary
I have a question about how to build multiple `.ipa` file.
My situation is now I can get maybe two `.ipa` file, and send a message to slack channel automatic, but there is just one `install page` button and just link to `QA.ipa`, I can just download one `ipa` by this way, I want to download all page by this way, how can I do this.
Thx~
![image](https://user-images.githubusercontent.com/42529593/52689449-26da8b00-2f95-11e9-84a2-f0f9f34528d3.png)
![image](https://user-images.githubusercontent.com/42529593/52689495-5d180a80-2f95-11e9-8934-b01445bb4824.png)

**Comment by fehersanyi-bitrise** [comment]
Hello there!

If you go to bitrise to the build page's app&s and artifacts tab you can download everything.
