### ISSUE TITLE
Version 1.4 asks for a directory path and does not accept the path to a file

### ISSUE THREAD

**Issue by SamuelDebruyn** [bitrise-steplib/steps-deploy-to-bitrise-io#83]
Since version 1.4.0 we are unable to deploy a file. The error message is `DeployPath: src/Droid/bin/Release/be.ourid-bitrise-signed.apk: not a directory`

**Comment by usmonster** [comment]
Same here—this is blocking some of our pipelines. A workaround is to pin to an earlier version, but it's not ideal.

**Comment by meyn** [comment]
doesn't work with the 1.4.1 version either (1.3.19 works though)

**Comment by trapacska** [comment]
Hey @rubenhorn !

Thanks for the report, the fix already implemented: #84

The new version of the step will be released soon.
