### ISSUE TITLE
deploy-to-bitrise fails if DeployPath not a directory

### ISSUE THREAD

**Issue by rubenhorn** [bitrise-steplib/steps-deploy-to-bitrise-io#85]
https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/blob/ad460f718d9c2f56b4863366ce14c00f166dd5b8/main.go#L28

Ever since this commit the step always fails, if I try to deploy a single file:
```
Issue with input: failed to parse config:
- DeployPath: /path/to/report.html: not a directory
```   

I'm going to further look into this, but I assume this is not the intended behaviour:
 https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/blob/24632320c6bece154b8adae4dbda6ef045981d41/step.yml#L26

**Comment by trapacska** [comment]
Hey @rubenhorn !

Thanks for the report, the fix already implemented: https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/pull/84

The new version of the step will be released soon.
