### ISSUE TITLE
Unsuccessful response after Uploading test result

### ISSUE THREAD

**Issue by gabriel-prado-ifood** [bitrise-steplib/steps-deploy-to-bitrise-io#87]
Hello Guys, im trying to upload our test results but Im getting this error.

Upload test results
- uploading (6) test results
Failed to upload test results: %!(EXTRA *errors.errorString=unsuccessful response code: 403
body:
{"error":"Unauthorized request"}
)

**Comment by kreeger** [comment]
Can verify that I'm getting the same thing. I'm rolling back to a previous version of this workflow (v1.4.1) step to see if this resolves it, but I'm not sure it will (this seems like a backend service issue).

**Comment by gabriel-prado-ifood** [comment]
Hello @kreeger , I'm getting it with bitrise.io deploy v1.4.0... Indeed, looks like backend issue.

**Comment by tamasbazs** [comment]
Hi @gabriel-prado-ifood , @kreeger 

Thanks so much for the report. We’re really sorry to be holding you up today! 😞

Please know that our Website team is aware of this issue and they are working hard to get everything up and running. We will send you a follow-up message here as soon as it's resolved.

Thank you for your patience! 🙌

**Comment by bitce** [comment]
Hi guys!

Just wanted to let you know that this should be solved and everything is back to normal, thanks for all your tireless patience and understanding! 🙂

**Comment by jamieadkins95** [comment]
@bitce We are seeing this issue again today

**Comment by bitce** [comment]
@jamieadkins95  could you include a build URL please?

**Comment by jamieadkins95** [comment]
https://app.bitrise.io/build/d1247c9f09e109a1

Only happened a couple of times yesterday, haven't had any problems today

**Comment by bitce** [comment]
Thanks! Consulted with the team and should have been a momentarily issue, but let us know if you experience this otherwise!

**Comment by gabriel-prado-ifood** [comment]
Thanks guys! Was solved 👍

**Comment by mqln** [comment]
I'm seeing this error today, but only for deploying our test log file. Is this something on your end, or have I borked a permission?

**Comment by kreeger** [comment]
Yeah, I'm seeing this pop up again, too.

**Comment by bitce** [comment]
Hi @mqln and @kreeger! Are you experiencing this consistently? This was possibly due to an incident we had yesterday, although the error should have been slightly different than the one originally reported here.

**Comment by kreeger** [comment]
@bitce It cleared up eventually!
