### ISSUE TITLE
Illegal character code, failed to upload test results

### ISSUE THREAD

**Issue by francescopretelli** [bitrise-steplib/steps-deploy-to-bitrise-io#88]
Lately I get the following error:
`Error during parsing test results: %!(EXTRA plist.plistParseError=plist: error parsing XML property list: XML syntax error on line 6074: illegal character code U+0008)` 

The build is shown as failed although it is actually successfully deployed and built, not sure what the error is about.

**Comment by bitce** [comment]
Hi @francescopretelli!

We're aware of the issue and currently working on the fix, thanks for your report!
