### ISSUE TITLE
No file found at path error

### ISSUE THREAD

**Issue by saudeoncovr** [bitrise-steplib/steps-deploy-to-bitrise-io#89]
When uploading test results, I am currently facing the following error:
`Error during parsing test results: %!(EXTRA *errors.errorString=No file found at path: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results532517436/test_result489868446/[REDACTED]/Test.xcresult/TestSummaries.plist)`

This is obviously after running the [xcode-test](https://github.com/bitrise-steplib/steps-xcode-test) step. The output of the tests state that they should be available.
```bash
Exporting test results
$ cp "-a" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/XCUITestOutput624749553/Test.xcresult" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results532517436/test_result489868446/[REDACTED]/"
```

This is using the latest version of deploy to bitrise.io, `1.4.2`.
Running on the `Xcode 11.0.x` stack.

**Comment by zachsimone** [comment]
+1. Getting the same error after building with Xcode 11 beta.

**Comment by bitce** [comment]
Hi guys, sorry to hear about the issues! Could you include build URLs we could take a look at?

**Comment by saudeoncovr** [comment]
@bitce https://app.bitrise.io/build/1ff27fea9f8a4fb9 here's one!

**Comment by zachsimone** [comment]
Hey @bitce, here's one of the builds that's just returned this error. https://app.bitrise.io/build/d62f0cb334bb75e2 
Let me know if I can provide more info. Thanks!

**Comment by bitce** [comment]
Hi @zachsimone @saudeoncovr,

Thanks for the details! Can you check if you experience the same issue with the new version of the step? The fix was recently released: https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/releases/tag/1.5.0

**Comment by zachsimone** [comment]
Hi @bitce, I just tried v1.5.0 for a build, and it worked perfectly. Thank you!

**Comment by saudeoncovr** [comment]
Yep, looks to be resolved @bitce, thanks!
