### ISSUE TITLE
Could not check if given project is macOS or not. No file found at path

### ISSUE THREAD

**Issue by cmarchal** [bitrise-steplib/steps-deploy-to-bitrise-io#97]
Hello,
First, thanks for your work !
I face an issue on version 1.7.0 of your step but everything is working fine with version 1.6.1.

Here is the error message: 

`deploy failed, error: could not check if given project is macOS or not, error: No file found at path: {path}/{app}.xcarchive/Info.plist`

Do you know what I can do to fix it ?

Thanks in advance !

**Comment by bitce** [comment]
Hi @cmarchal, can you please include a build URL so we could check out the related logs?

**Comment by cmarchal** [comment]
Sure, here it is : https://app.bitrise.io/build/84f9887ffd88704f

**Comment by bitce** [comment]
Hi @cmarchal!

Thanks. Sorry for the delay, unfortunately, we'd need your .xcarchive folder and the related project files. Could we contact us via e-mail at letsconnect@bitrise.io or on the on-site chat and send them over so we can conclude the investigation?

**Comment by notjosh** [comment]
Bumping this issue with some new information, as I just tried to upgrade from 1.6.1.

The `.xcarchive` filename seems to be used to assume the name of the contents of the zip, which in our case is different (to match some other naming conventions). A concrete example here is:

```
$ ls
TestFlight Debug-Debug-1.4.4-929.xcarchive.zip
$ unzip -qq ./TestFlight\ Debug-Debug-1.4.4-929.xcarchive.zip
$ ls
TestFlight Debug 2020-01-24 09.53.26.xcarchive
TestFlight Debug-Debug-1.4.4-929.xcarchive.zip
```

The line at fault is here: https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/blob/b311804b6b9bcbb4635210b2de06c474e7e26693/uploaders/xcarchiveuploader.go#L22

I've rolled back to 1.6.1 for now, and it's working again.

**Comment by bitce** [comment]
Hi @notjosh thanks a lot for the details? This is happening on the latest version of the step, right? Can you please also send a build URL for us to look at?

**Comment by notjosh** [comment]
> This is happening on the latest version of the step, right? 

Yes, 1.9.5.

> Can you please also send a build URL for us to look at?

Sure! https://app.bitrise.io/build/db796ae56c7866fe

**Comment by bitce** [comment]
Hi @notjosh!

Sorry for the insane delay here! Can you please send us your .xcarchive folder and the related project files. Could we contact us via e-mail at letsconnect@bitrise.io or on the on-site chat and send them over so we can conclude the investigation?

**Comment by notjosh** [comment]
Hiya @bitce, no problem on the delay, I worked around the issue so it's not really a blocker for us at all. Just hoping not to update past 1.6.1 any time soon ;)

> Can you please send us your .xcarchive folder and the related project files.

I, uhhh, don't really have that around now, but it's not really specifically related to the issue. There should be enough information in simply "the zip filename does not match the filename of the contents" for you to go on, I'd think?

**Comment by bitce** [comment]
Glad to hear it not being a blocker!

This was something specifically requested earlier about the problem from our Tooling team. I can't really say for certain what would be enough to go on, but based on the error message being about not finding the file, which is clearly there, I would suspect it to be relevant.

**Comment by notjosh** [comment]
Nonono, it's the _container_ `.zip` (which contains a `xcarchive` file) that is the issue here. The actual `.xcarchive` is completely irrelevant, as per my example.

To reiterate explicitly: there's a `.xcarchive.zip` file, which contains a `.xcarchive` file.

The script can't find the `.xcarchive` file because it's assuming the filename is the same as the `.zip`'s file name, that's all. Nothing specific about the `.xcarchive`, only the `.zip` that contains an `.xcarchive` file.

I can...make you a zip file with a file in it with a different name if you really want (since I don't have the `.xcarchive.zip` to hand), but I feel like that's almost condescending?

**Comment by non-binary** [comment]
This is a known issue and we already have the card created for this to be solved. We will let you know once it has been fixed.

**Comment by cohen72** [comment]
@non-binary I'm experiencing the same error, but in my case I'm using Fastlane `gym` to create the `.xcarchive` file and then zipping it up and placing it within the `BITRISE_DEPLOY_DIR` folder.  

Has anyone else has had any success using Fastlane `gym` together with the deploy for bitrise.io step? Perhaps I'm missing some parameters on `gym` that may be what's causing this issue.  If anyone has had success using `gym`, could they post their code?  Thanks :)

**Comment by notjosh** [comment]
@cohen72 we're using Fastlane too. Our setup still works if you roll back the version of this plugin to before the breaking change was made (1.6.1 is still working perfectly for us). Not sure if new features have been added that you rely on though :/
